name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "image tag"
        required: true
        default: latest

jobs:
  trigger-build:
    uses: .github/workflows/wokflow-1.yaml
    with:
       image_tag: ${{ github.events.inputs.image_tag }}