name: Manual work flow check
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Please give an image name"
        required: true
        default: "build_app"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          TAG="latest"
          docker build -t $IMAGE_NAME:$TAG .
          