name: Manual Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Enter the Docker tag version (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"

env:
  AWS_REGION: ap-south-1
  ECR_REPO: github_action_demo # your ECR repository name
  IMAGE_NAME: github-action-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          echo "Building Docker image with tag: ${{ github.event.inputs.tag_name }}"
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag_name }} .

      - name: Tag Docker image for ECR
        run: |
          ECR_URI=${{ steps.login-ecr.outputs.registry }}
          docker tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag_name }} \
                     $ECR_URI/${{ env.ECR_REPO }}:${{ github.event.inputs.tag_name }}

      - name: Push Docker image to ECR
        run: |
          ECR_URI=${{ steps.login-ecr.outputs.registry }}
          docker push $ECR_URI/${{ env.ECR_REPO }}:${{ github.event.inputs.tag_name }}
          echo "Image pushed successfully: $ECR_URI/${{ env.ECR_REPO }}:${{ github.event.inputs.tag_name }}"