name: First Pipeline
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Hello from GitHub Actions!"