name: Manual Workflow
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        default: latest
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building docker image
        run: docker build -t my-nginx:${{ github.event.inputs.image_tag }} .