name: Env vs Output Example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.set_output.outputs.build_number }}

    steps:
      - name: Set environment variable
        run: echo "GREETING=Hello from build job" >> $GITHUB_ENV

      - name: Use environment variable
        run: echo "$GREETING"

      - name: Set step output
        id: set_output
        run: echo "build_number=123" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Try using env variable (won't work)
        run: echo "GREETING is '$GREETING' because env vars don't persist across jobs"

      - name: Use job output from previous job
        run: echo "Deploying build number ${{ needs.build.outputs.build_number }}"